[package]
name = "bin"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.20", features = ["derive", "env", "wrap_help"] }
serde_json = "1.0.132"
slack_client = { path = "../lib" }
tokio = { version = "1.41.1", features = ["full"] }
jiff = "0.1.14"
