[package]
name = "slack_api"
version.workspace = true
edition.workspace = true

[dependencies]
reqwest.workspace = true
serde.workspace = true

# To Markdown
mrkdwn2markdown = { git = "https://github.com/0x6b/mrkdwn2markdown", tag = "v0.3.0" }
